name: Mein erster Workflow

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set Environment Variable
        run: echo "MEINE_VARIABLE=true" >> $GITHUB_ENV

      - name: Conditional Step
        if: ${{ env.MEINE_VARIABLE == 'true' }}
        run: echo "Dieser Schritt wird nur ausgeführt, wenn MEINE_VARIABLE gesetzt und true ist."
