name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Run npm tests
        run: |
          npm install
          npm test

      - name: Print CI message
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "This is a simple CI pipeline!"
