name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Checkout des Repositories
      - name: Checkout repository
        uses: actions/checkout@v2

      # Schritt 2: Installiere Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Schritt 3: Führe Tests aus
      - name: Run npm tests
        run: |
          npm install
          npm test
